version: "3"
services:
  blockchain:
    restart: always
    build: .
    working_dir: "/root/src"
    tty: true
    ports:
      - "${IP}:5050:5050"
      - "${IP}:8080:8080"
    networks:
      - net1
    volumes:
      - ./src:/root/src

networks:
  net1:
    driver: 'bridge'
    external: true
